<!-- item will be appened to this layout -->
<!-- <div id="log" class="sl__chat__layout">
</div> -->

<!-- chat item -->
<!-- <script type="text/template" id="chatlist_item"> -->
<div data-from="<?= $from ?>" data-id="<?= $messageId ?>">
    <span class="meta">
      <span class="badges">
      </span>
      <span class="name"><?= $from ?></span>
    </span>

    <div class="bull">
      <span class="message">
        <?= $message ?>
      </span>
      <div class="float-icone">
        <img class="icone" src="https://cdn.discordapp.com/attachments/446049284694081546/1038646987706343495/icone.png" alt="icone">
      </div>
    </div>
</div>
<!-- </script> -->